// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qyUWOsDPXssRHM8hy-xjCKmaz3NmcI4',
    appId: '1:17640065619:web:f146ba7ae8a6277fce94a6',
    messagingSenderId: '17640065619',
    projectId: 'finalapp-12f67',
    authDomain: 'finalapp-12f67.firebaseapp.com',
    storageBucket: 'finalapp-12f67.firebasestorage.app',
    measurementId: 'G-17V9G8CDV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM42RbnyfE_nWCAShJ9LW6NoJcpMpSgKY',
    appId: '1:17640065619:android:d94258c79df96328ce94a6',
    messagingSenderId: '17640065619',
    projectId: 'finalapp-12f67',
    storageBucket: 'finalapp-12f67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcpoLQQZmirMzi7_eIukKJj9OAkIiS1k',
    appId: '1:17640065619:ios:b1594adf57af221ece94a6',
    messagingSenderId: '17640065619',
    projectId: 'finalapp-12f67',
    storageBucket: 'finalapp-12f67.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHcpoLQQZmirMzi7_eIukKJj9OAkIiS1k',
    appId: '1:17640065619:ios:b1594adf57af221ece94a6',
    messagingSenderId: '17640065619',
    projectId: 'finalapp-12f67',
    storageBucket: 'finalapp-12f67.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4qyUWOsDPXssRHM8hy-xjCKmaz3NmcI4',
    appId: '1:17640065619:web:a72e46a500269504ce94a6',
    messagingSenderId: '17640065619',
    projectId: 'finalapp-12f67',
    authDomain: 'finalapp-12f67.firebaseapp.com',
    storageBucket: 'finalapp-12f67.firebasestorage.app',
    measurementId: 'G-4SEH0Z4589',
  );
}
